name: minimap2
channels:
  - bioconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - htslib=1.21=h566b1c6_1
  - k8=1.2=he8db53b_5
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - libcurl=8.12.1=h332b0f4_0
  - libdeflate=1.23=h4ddbbb0_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - liblzma=5.6.4=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libzlib=1.3.1=hb9d3cd8_2
  - minimap2=2.28=h577a1d6_4
  - ncurses=6.5=h2d0b736_3
  - openssl=3.4.1=h7b32b05_0
  - python_abi=3.13=5_cp313
  - samtools=1.21=h96c455f_1
  - sysroot_linux-64=2.17=h0157908_18
  - tzdata=2025b=h78e105d_0
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/kimani/miniconda3/envs/minimap2
